type PesapalOrder = { merchantReference: string; amount: number; currency: string; description: string; customer: { name: string; email: string; phone: string } };
const baseUrl = (process.env.PESAPAL_BASE_URL || 'https://pay.pesapal.com/v3').replace(/\/$/, '');
let cachedToken: { value: string; expires: number } | undefined;
async function api(path: string, init: RequestInit = {}) { const response = await fetch(`${baseUrl}${path}`, { ...init, headers: { 'Content-Type': 'application/json', ...(init.headers || {}) }, cache: 'no-store' }); if (!response.ok) throw new Error(`PesaPal request failed (${response.status})`); return response.json(); }
export async function getPesapalToken() { if (cachedToken && cachedToken.expires > Date.now()) return cachedToken.value; const data = await api('/api/Auth/RequestToken', { method: 'POST', body: JSON.stringify({ consumer_key: process.env.PESAPAL_CONSUMER_KEY, consumer_secret: process.env.PESAPAL_CONSUMER_SECRET }) }); if (!data.token) throw new Error('PesaPal did not return an access token.'); cachedToken = { value: data.token, expires: Date.now() + 4 * 60 * 1000 }; return data.token; }
async function authorized(path: string, init: RequestInit = {}) { return api(path, { ...init, headers: { Authorization: `Bearer ${await getPesapalToken()}`, ...(init.headers || {}) } }); }
export async function registerIpnUrl() { if (process.env.PESAPAL_IPN_ID) return process.env.PESAPAL_IPN_ID; const data = await authorized('/api/URLSetup/RegisterIPN', { method: 'POST', body: JSON.stringify({ url: process.env.PESAPAL_IPN_URL, ipn_notification_type: 'GET' }) }); if (!data.ipn_id) throw new Error('PesaPal did not return an IPN ID. Configure PESAPAL_IPN_ID after registration.'); return data.ipn_id as string; }
export async function submitOrder(order: PesapalOrder) { const ipnId = await registerIpnUrl(); return authorized('/api/Transactions/SubmitOrderRequest', { method: 'POST', body: JSON.stringify({ id: order.merchantReference, currency: order.currency, amount: order.amount, description: order.description, callback_url: process.env.PESAPAL_CALLBACK_URL, notification_id: ipnId, billing_address: { email_address: order.customer.email, phone_number: order.customer.phone, first_name: order.customer.name } }) }); }
export async function getTransactionStatus(trackingId: string) { return authorized(`/api/Transactions/GetTransactionStatus?orderTrackingId=${encodeURIComponent(trackingId)}`); }
