'use client';

import { useEffect, useState } from 'react';

type Item = Record<string, any>;
const definitions: Record<string, { label: string; fields: string[] }> = {
  solutions: { label: 'Solutions', fields: ['slug', 'title', 'tagline', 'targetAudience', 'problem', 'solution', 'features', 'benefits', 'published'] },
  industries: { label: 'Industries', fields: ['slug', 'name', 'description', 'useCases', 'published'] },
  demos: { label: 'Demos', fields: ['title', 'description', 'demoUrl', 'features', 'published'] },
  caseStudies: { label: 'Case studies', fields: ['slug', 'title', 'clientName', 'challenge', 'solution', 'features', 'technologies', 'impact', 'published'] },
};
const lists = new Set(['features', 'benefits', 'useCases', 'technologies', 'impact']);
export default function AdminCMS() {
  const [type, setType] = useState('solutions'); const [items, setItems] = useState<Item[]>([]); const [editing, setEditing] = useState<Item | null>(null); const [notice, setNotice] = useState('');
  const load = () => fetch(`/api/admin/content?type=${type}`).then(r => r.json()).then(data => setItems(Array.isArray(data) ? data : []));
  useEffect(() => { void load(); }, [type]);
  const fields = definitions[type].fields;
  async function save(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const fd = new FormData(event.currentTarget); const payload = Object.fromEntries(fields.map(field => [field, field === 'published' ? fd.get(field) === 'on' : fd.get(field) || ''])); if (editing?.id) payload.id = editing.id; const response = await fetch(`/api/admin/content?type=${type}`, { method: editing?.id ? 'PATCH' : 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) }); if (response.ok) { setEditing(null); setNotice('Saved successfully.'); load(); } else setNotice('Unable to save this item.'); }
  async function remove(id: string) { if (!confirm('Delete this item?')) return; const response = await fetch(`/api/admin/content?type=${type}&id=${id}`, { method: 'DELETE' }); if (response.ok) load(); }
  return <section className="mt-10 grid lg:grid-cols-[1fr_1.1fr] gap-8"><div className="rounded-2xl border border-slate-800 bg-slate-900 p-6"><div className="flex gap-2 flex-wrap">{Object.entries(definitions).map(([key, value]) => <button key={key} onClick={() => { setType(key); setEditing(null); }} className={`px-3 py-2 rounded-lg text-sm ${type === key ? 'bg-blue-600 text-white' : 'bg-slate-800 text-slate-300'}`}>{value.label}</button>)}</div><div className="mt-6 flex items-center justify-between"><h2 className="text-xl font-bold text-white">{definitions[type].label}</h2><button onClick={() => setEditing({ published: true })} className="text-sm text-blue-400">+ New</button></div><div className="mt-4 space-y-3">{items.map(item => <div key={item.id} className="rounded-xl border border-slate-800 bg-slate-950 p-4 flex items-center justify-between gap-3"><div><p className="font-semibold text-white">{item.title || item.name}</p><p className="text-xs text-slate-500">{item.slug || item.clientName || 'No slug'}</p></div><div className="flex gap-3 text-sm"><button onClick={() => setEditing(item)} className="text-blue-400">Edit</button><button onClick={() => remove(item.id)} className="text-red-400">Delete</button></div></div>)}{items.length === 0 && <p className="text-sm text-slate-500">No content yet.</p>}</div></div>{editing && <form onSubmit={save} className="rounded-2xl border border-slate-800 bg-slate-900 p-6"><div className="flex justify-between"><h2 className="text-xl font-bold text-white">{editing.id ? 'Edit' : 'New'} {definitions[type].label.slice(0, -1)}</h2><button type="button" onClick={() => setEditing(null)} className="text-slate-400">Cancel</button></div><div className="mt-5 space-y-4">{fields.map(field => field === 'published' ? <label key={field} className="flex gap-2 text-sm text-slate-300"><input type="checkbox" name={field} defaultChecked={editing[field] !== false}/> Published</label> : <label key={field} className="block text-xs text-slate-400 capitalize">{field.replace(/([A-Z])/g, ' $1')} {lists.has(field) && '(one per line)'}{['problem','solution','description','challenge',...lists].includes(field) ? <textarea required={!lists.has(field)} name={field} defaultValue={Array.isArray(editing[field]) ? editing[field].join('\n') : editing[field] || ''} className="mt-1 w-full min-h-24 rounded-lg bg-slate-950 border border-slate-700 p-3 text-sm text-white"/> : <input required={['slug','title','name','tagline'].includes(field)} name={field} defaultValue={editing[field] || ''} className="mt-1 w-full rounded-lg bg-slate-950 border border-slate-700 p-3 text-sm text-white"/>}</label>)}</div><button className="mt-6 rounded-xl bg-blue-600 px-5 py-3 font-bold text-white">Save changes</button>{notice && <p className="mt-3 text-sm text-emerald-400">{notice}</p>}</form>}</section>;
}
